### ISSUE TITLE
ithc in HID Mode fails when using pen

### ISSUE THREAD

**Issue by lxdb** [quo/ithc-linux#12]
When trying to write with the Surface Pen on Surface Pro 7+ using the latest ithc driver (with enabled hid) with linux-surface iptsd on Fedora, the driver stops working with `[   82.626291] ithc 0000:00:10.6: ithc_dma_rx_process_buf: hid_input_report failed with -1` in dmesg.

**Comment by quo** [comment]
Does the error appear immediately or randomly? Does the error repeat or does it just appear once?

Can you do the following:
- run `sudo cat /dev/ithc > ithc.dat` and leave it running
- reproduce the error
- stop the above `cat` command with Ctrl+C
- attach the ithc.dat file that was created

**Comment by StollD** [comment]
`hid_input_report` will reject reports that are either 0 in size, or that don't appear in the HID report descriptor. I ran into a similar error on IPTS recently: https://github.com/linux-surface/intel-precise-touch/issues/18 (starts off with another issue). 

In my case it was because the function to get the native report descriptor of the device did not include the singletouch descriptor, but since iptsd is running this doesnt seem to be the issue here.

**Comment by lxdb** [comment]
> Does the error appear immediately or randomly? Does the error repeat or does it just appear once?
> 
> Can you do the following:
> 
>     * run `sudo cat /dev/ithc > ithc.dat` and leave it running
> 
>     * reproduce the error
> 
>     * stop the above `cat` command with Ctrl+C
> 
>     * attach the ithc.dat file that was created

Here the ithc.dat you requested; https://fileupload.ggc-project.de/download/da8d815f41048d0a/#0ur9wWB8ytAXSvWA4VbgKA . I had to upload it somewhere else because GitHub didn't accept it.
I have to correct my report, actually the error happens not when writing with the pen, but when (at least it seems like...) the hand recognition launches. It happens every time and immediately.

**Comment by quo** [comment]
Thanks. I don't see any empty packets. But there is one slightly corrupted packet (it almost looks like a few bytes went missing, causing the end of the packet to be shifted a bit). This would probably cause iptsd to crash, but I don't see how it would cause hid_input_report to fail.

Do you not get any errors from iptsd?

Also, can you post the full output of `sudo dmesg | grep ithc`?

**Comment by lxdb** [comment]
Full dmesg output:
```
[denys@SP-DK-L ~]$ sudo dmesg | grep -i ithc
[    5.735422] ithc: loading out-of-tree module taints kernel.
[    5.771552] ithc 0000:00:10.6: enabling device (0000 -> 0002)
[    5.885776] ithc 0000:00:10.6: config: e0000402 00000000 000a00ff 0000001c 0000001c 43495424 fda00a2e 0c1a045e 00000001 05008d8b 00000000 00000000 00000000 0404035e 000001c0 00000002
[    5.886174] ithc 0000:00:10.6: registered device ithc
[    6.034734] hid-generic 0001:045E:0C1A.0003: input,hidraw1: <UNKNOWN> HID v1.00 Device [Intel Touch Host Controller] on pci-0000:00:10.6/ithc
[  105.173168] ithc 0000:00:10.6: ithc_dma_rx_process_buf: hid_input_report failed with -1
```
iptsd log:
```
[denys@SP-DK-L ~]$ sudo systemctl status iptsd@-dev-hidraw1.service
× iptsd@-dev-hidraw1.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd@.service; static)
     Active: failed (Result: exit-code) since Sat 2022-08-20 15:03:36 CEST; 19s ago
   Duration: 1min 42.286s
       Docs: https://github.com/linux-surface/iptsd
    Process: 818 ExecStart=/usr/local/bin/iptsd /dev/hidraw1 (code=exited, status=1/FAILURE)
   Main PID: 818 (code=exited, status=1/FAILURE)
        CPU: 44ms

Aug 20 15:01:54 SP-DK-L systemd[1]: Started iptsd@-dev-hidraw1.service - Intel Precise Touch & Stylus Daemon.
Aug 20 15:01:54 SP-DK-L iptsd[818]: [15:01:54.129] [info] Connected to device 045E:0C1A
Aug 20 15:03:36 SP-DK-L iptsd[818]: [15:03:36.337] [error] narrowing_error
Aug 20 15:03:36 SP-DK-L iptsd[818]: [15:03:36.338] [info] Stopping
Aug 20 15:03:36 SP-DK-L systemd[1]: iptsd@-dev-hidraw1.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 15:03:36 SP-DK-L systemd[1]: iptsd@-dev-hidraw1.service: Failed with result 'exit-code'.
```

**Comment by StollD** [comment]
Your iptsd is crashing, so this could actually be the same issue as on IPTS, where singletouch reports were rejected because the report descriptor was missing. Does the same happen if you dont have iptsd running?

Regarding the iptsd crash, it seems like this is the same issue as https://github.com/linux-surface/iptsd/issues/65. I asked for a coredump in that issue so I could see where the error is, but didnt get a reply. Maybe you could follow the steps in that issue?

**Comment by quo** [comment]
Also make sure you have the latest iptsd; a narrowing_error was fixed in https://github.com/linux-surface/iptsd/commit/b9a1f1f66a42af350f3def66616be2891ac41e6e.

**Comment by lxdb** [comment]
> Your iptsd is crashing, so this could actually be the same issue as on IPTS, where singletouch reports were rejected because the report descriptor was missing. Does the same happen if you dont have iptsd running?
> 
> Regarding the iptsd crash, it seems like this is the same issue as [linux-surface/iptsd#65](https://github.com/linux-surface/iptsd/issues/65). I asked for a coredump in that issue so I could see where the error is, but didnt get a reply. Maybe you could follow the steps in that issue?

Here is the coredump you asked for: https://fileupload.ggc-project.de/download/563a15d3b043364d/#N-PvrzaPrcOi8iF9aa3WbQ
I use the latest iptsd from master.
I don't understand how the error can happen without iptsd running - it only happens when it detects my hand when simultaneously using the pen, which does not work without iptsd.

**Comment by StollD** [comment]
> Here is the coredump you asked for: https://fileupload.ggc-project.de/download/563a15d3b043364d/#N-PvrzaPrcOi8iF9aa3WbQ. I use the latest iptsd from master.

Thank you! I pushed a fix for the issue to the master branch.

> I don't understand how the error can happen without iptsd running - it only happens when it detects my hand when simultaneously using the pen, which does not work without iptsd.

When iptsd crashes the kernel module should go back into singletouch mode. Since your hand is touching the display, there will be singletouch data generated immideately. 

On IPTS, the issue that `hid_input_report` would return -1 occured when the HID descriptor didnt contain information about the singletouch reports, so the kernel rejected them.

The test for this is pretty simple: Load the kernel module, make sure that iptsd is not running, and touch the screen. Either singletouch works and you get no error, or it doesnt work and you get the error you reported.

I think these are two different issues: One issue in iptsd, and one issue in the singletouch implementation of ITHC. The iptsd issue is not related to the other one, but it cause a situation that exposed you to the ithc issue.

**Comment by lxdb** [comment]
> > Here is the coredump you asked for: https://fileupload.ggc-project.de/download/563a15d3b043364d/#N-PvrzaPrcOi8iF9aa3WbQ. I use the latest iptsd from master.
> 
> Thank you! I pushed a fix for the issue to the master branch.
> 
> > I don't understand how the error can happen without iptsd running - it only happens when it detects my hand when simultaneously using the pen, which does not work without iptsd.
> 
> When iptsd crashes the kernel module should go back into singletouch mode. Since your hand is touching the display, there will be singletouch data generated immediately.
> 
> On IPTS, the issue that `hid_input_report` would return -1 occured when the HID descriptor didnt contain information about the singletouch reports, so the kernel rejected them.
> 
> The test for this is pretty simple: Load the kernel module, make sure that iptsd is not running, and touch the screen. Either singletouch works and you get no error, or it doesnt work and you get the error you reported.
> 
> I think these are two different issues: One issue in iptsd, and one issue in the singletouch implementation of ithc. The iptsd issue is not related to the other one, but it cause a situation that exposed you to the ithc issue.

Thank you very much! Now it works the way it should.
I still get the ithc error message, even though it does not have any impact on the functionality. When stopping iptsd I still can use the touchscreen in singeltouch mode without any error messages.

**Comment by NP-chaonay** [comment]
> hand recognition

**reply to lxdb** idk if you mean "palm detection"?

**Comment by quo** [comment]
Can you upload the file `/sys/class/hidraw/hidraw1/device/report_descriptor`? (I doubt the report descriptor is different from mine, but you do have a different firmware version (5.0.141.139 vs 5.0.138.139), so who knows.)

Can you also apply the following patch to ithc, and post dmesg output after reproducing the error again? With the patch it should print the report id and size when hid_input_report fails.

```patch
diff --git a/src/ithc-dma.c b/src/ithc-dma.c
index 630807d..35b4b98 100644
--- a/src/ithc-dma.c
+++ b/src/ithc-dma.c
@@ -181,7 +181,8 @@ static int ithc_dma_rx_process_buf(struct ithc *ithc, struct ithc_dma_data_buffe
                WRITE_ONCE(ithc->hid_parse_done, true);
                wake_up(&ithc->wait_hid_parse);
        } else if (ithc->hid && hdr->code == DMA_RX_CODE_INPUT_REPORT) {
-               CHECK(hid_input_report, ithc->hid, HID_INPUT_REPORT, hiddata, hdr->data_size, 1);
+               if (CHECK(hid_input_report, ithc->hid, HID_INPUT_REPORT, hiddata, hdr->data_size, 1) < 0)
+                       pci_err(ithc->pci, "hid report 0x%x, size %u\n", hiddata[0], hdr->data_size);
        } else if (ithc->hid && hdr->code == DMA_RX_CODE_FEATURE_REPORT) {
                bool done = false;
                mutex_lock(&ithc->hid_get_feature_mutex);
@@ -193,7 +194,8 @@ static int ithc_dma_rx_process_buf(struct ithc *ithc, struct ithc_dma_data_buffe
                }
                mutex_unlock(&ithc->hid_get_feature_mutex);
                if (done) wake_up(&ithc->wait_hid_get_feature);
-               else CHECK(hid_input_report, ithc->hid, HID_FEATURE_REPORT, hiddata, hdr->data_size, 1);
+               else if (CHECK(hid_input_report, ithc->hid, HID_FEATURE_REPORT, hiddata, hdr->data_size, 1) < 0)
+                       pci_err(ithc->pci, "hid report 0x%x, size %u\n", hiddata[0], hdr->data_size);
        } else {
                pci_dbg(ithc->pci, "unhandled dma rx data! channel %u, buffer %u, size %u, code %u\n", channel, buf, len, hdr->code);
                print_hex_dump_debug(DEVNAME " data: ", DUMP_PREFIX_OFFSET, 32, 1, hdr, min(len, 0x400u), 0);
```
